const briefDate = "2026-08-06";

const tasks = [
  { number: "01", title: "先把身体拉回可用状态", body: "昨天日记记录四点入睡，白天还有较多体力劳动；近一周也多次出现晚睡、通宵与白天补觉。今天没有可确认的既定日程，先补水、吃一顿正常的饭、洗漱并短暂走动；不靠高咖啡因或空腹运动硬顶。", first: "喝水并吃一顿正常的饭", time: "45–60 分钟", tone: "mint" },
  { number: "02", title: "写清一条视频的锚点", body: "这是 AI 建议，不是既有承诺。只写一句：这条 AI 知识库内容要帮谁解决什么问题、希望对方记住什么。再用一个真实场景和两条原始记录支撑它；不要求先得到完整正确答案。", first: "写下“我要帮助谁、让他少走哪一步”", time: "25–35 分钟", tone: "blue" },
  { number: "03", title: "录一段可修改的 60 秒口述", body: "只把第二项的骨架讲出来，先录音再决定是否录像。卡住时回到逻辑结构，不继续补课程、扩建系统或反复找新的方法。第一版用于暴露表达问题，不等于要公开发布。", first: "不看逐字稿，直接说第一遍", time: "20–30 分钟", tone: "peach" },
];

const creatorUpdates = [
  { tag: "Dan Koe", title: "未发现可核验的 8 月 5 日更新", intro: "不以历史观点补齐“昨日动态”。", content: ["未发现能够准确核验为 8 月 5 日发布、且可以读取完整上下文的 X 帖子、Newsletter 或长文。", "因此本期不使用历史观点补充“昨日动态”。", "早报分析 / 建议：在博主没有可靠更新时，栏目保留空缺，而不是为了完整而重复旧观点。信息系统的可信度，往往来自它愿意承认“今天没有数据”。"], source: "https://thedankoe.com/", sourceLabel: "Dan Koe 公开主页" },
  { tag: "dontbesilent", title: "未发现可核验的 8 月 5 日 X 或抖音内容", intro: "dbskill 的公开资料仅作背景，未被写成昨日更新。", content: ["未发现可以明确确认于 8 月 5 日发布的 X 或抖音公开内容。", "dbskill 当前可核验的公开最新版仍为 v2.12.0，主要改动是补齐 /dbs-decision 与诊断、目标、对标、好问题等 Skill 的主路径联动，并增加一张 Skill 联动图。仓库目前把知识原子、主题分类与可调用 Skill 进行关联，使知识不只被保存，而是能够进入具体任务。", "早报分析：真正值得借鉴的不是 Skill 数量，而是它的结构：原始内容 → 知识原子 → 适用主题 → 对应 Skill → 实际任务。", "这正好回应 AI 知识库视频容易出现的问题：展示了“资料能被搜出来”，却没有解释“搜出来以后，它进入了哪个决策或行动”。"], source: "https://github.com/dontbesilent2025/dbskill", sourceLabel: "dbskill 公开仓库" },
  { tag: "Naval", title: "官网和播客未显示 8 月 5 日新增节目", intro: "最新完整节目仍是 7 月 2 日《Live in the Future》。", content: ["Naval 官网和播客平台没有显示 8 月 5 日新增节目。当前最新完整节目仍是 7 月 2 日发布的《Live in the Future》。", "本期不将旧节目冒充昨日更新。"], source: "https://nav.al/", sourceLabel: "Naval 官网" },
  { tag: "姜胡说", title: "未发现可完整核验的 8 月 5 日公开短视频", intro: "只看本人抖音 / 视频号，不以转载或旧视频补位。", content: ["未找到能够可靠确认于 8 月 5 日发布、同时可以获得完整口播与准确发布时间的抖音或视频号内容。", "公开搜索能找到其部分历史抖音视频及 AI 文稿，但没有足够证据证明属于昨日更新，因此不纳入本期动态。"], source: "https://www.douyin.com/search/%E5%A7%9C%E8%83%A1%E8%AF%B4", sourceLabel: "姜胡说抖音公开搜索" },
];

const weather = { location: "南宁", condition: "多云有雷阵雨", temperature: "24–32℃", icon: "⛈️" };

function SourceLink({ href, label }: { href: string; label: string }) {
  return <p><a className="archive-link" href={href}>阅读原始来源：{label} ↗</a></p>;
}

export default function Home() {
  return (
    <main data-brief-date={briefDate}>
      <header className="topbar">
        <a className="brand" href="#top" aria-label="返回顶部"><span className="brand-dot" />蔓蔓的早课</a>
        <div className="top-actions">
          <button className="menu-button" type="button" aria-label="打开阅读目录" aria-controls="content-menu" aria-expanded="false" data-menu-button><span /><span /><span /></button>
          <details className="date-picker"><summary aria-label="选择简报日期"><span className="calendar-symbol" aria-hidden="true">▦</span><span>{briefDate.replaceAll("-", ".")}</span><span className="chevron">⌄</span></summary><nav className="date-list" data-archive-list="true" aria-label="选择过往简报日期"><a href="?date=2026-08-06" aria-current="page">2026年8月6日</a></nav></details>
          <div className="status"><span className="status-dot" />每天自动更新</div>
        </div>
      </header>
      <button className="sidebar-overlay" type="button" aria-label="关闭阅读目录" data-menu-close />
      <div className="app-shell">
        <aside className="sidebar" id="content-menu" aria-label="简报阅读目录">
          <div className="sidebar-head"><div><span className="sidebar-kicker">CONTENTS</span><strong>今天看什么</strong></div><button className="menu-close" type="button" aria-label="关闭阅读目录" data-menu-close>×</button></div>
          <nav className="sidebar-nav">
            <details className="nav-group" data-nav-group><summary className="nav-title"><span className="nav-icon icon-focus">✓</span><span>今日计划</span><span className="nav-chevron">⌄</span></summary><div className="nav-sub">{tasks.map((task, i) => <a href={`#task-${i + 1}`} key={task.title}>{task.title}</a>)}<a href="#schedule">今日时间块</a><a href="#risk">今日风险</a></div></details>
            <details className="nav-group" data-nav-group><summary className="nav-title"><span className="nav-icon icon-briefing">▤</span><span>每日资讯</span><span className="nav-chevron">⌄</span></summary><div className="nav-sub">{creatorUpdates.map((item, i) => <a href={`#creator-${i + 1}`} key={item.tag}>{item.tag}：{item.title}</a>)}<a href="#story-1">1. Disney 与 TikTok 合作</a><a href="#story-2">2. AI 虚拟博主与透明度</a><a href="#story-3">3. Disney+ 与创作者生命周期</a><a href="#story-4">4. YouTube 评论语义搜索</a><a href="#story-5">5. AI 内容与原创定义</a><a href="#product-observation">产品观察</a><a href="#early-action">今日行动建议</a></div></details>
            <details className="nav-group" data-nav-group><summary className="nav-title"><span className="nav-icon icon-planet">✦</span><span>姜胡说</span><span className="nav-chevron">⌄</span></summary><div className="nav-sub"><a href="#planet-1">大胡子：mcp_vault 与知识重构</a><a href="#planet-2">大胡子：阅读是拆解</a><a href="#planet-3">大胡子：知识库三层</a><a href="#xiaobaotong-1">小报童：输出力与锚点</a></div></details>
            <details className="nav-group" data-nav-group><summary className="nav-title"><span className="nav-icon icon-review">↺</span><span>复盘</span><span className="nav-chevron">⌄</span></summary><div className="nav-sub"><a href="#yesterday-review">昨日复盘</a><a href="#seven-day-trend">近七天趋势</a><a href="#action-diagnosis">AI 执行力诊断</a></div></details>
            <details className="nav-group" data-nav-group><summary className="nav-title"><span className="nav-icon icon-briefing">↗</span><span>今日深读</span><span className="nav-chevron">⌄</span></summary><div className="nav-sub"><a href="#deep-read-1">Wired：AI 虚拟博主</a><a href="#deep-read-2">Disney 与 TikTok 合作</a><a href="#deep-read-3">AI 与出版行业证据综述</a></div></details>
            <details className="nav-group" data-nav-group><summary className="nav-title"><span className="nav-icon icon-hotlist">↗</span><span>热点榜单</span><span className="nav-chevron">⌄</span></summary><div className="nav-sub"><a href="#hotlist">查看 2026 年 8 月 5 日完整榜单</a></div></details>
          </nav>
          <p className="sidebar-note">点小标题直达正文 · 折叠内容会自动展开</p>
        </aside>

        <div className="page" id="top">
          <section className="hero">
            <div className="date-block"><div className="date-day">06</div><div><p className="date-month">2026 · 08</p><p className="date-week">星期四</p></div></div>
            <div className="hero-copy"><p className="eyebrow">TODAY&apos;S DIRECTION</p><h1>恢复节律，<br />再做一个可修改的表达。</h1><p className="judgment">昨天生日仍熬至四点，外出体力劳动后没有记录新的产出；近一周睡眠紊乱与输入、系统工作反复挤占行动。今天恢复优先，只推进一个低风险的表达草稿。</p></div>
            <div className="hero-weather" aria-label={`${weather.location}当天天气：${weather.condition}，${weather.temperature}`}><span className="weather-icon">{weather.icon}</span><span className="weather-copy"><strong>{weather.condition}</strong><small>{weather.location} · {weather.temperature}</small></span></div>
          </section>

          <section className="section" id="today">
            <div className="section-heading compact-heading"><div><p className="eyebrow">THREE PRIORITIES</p><h2>今天只做三件事</h2></div><p>AI 建议：恢复优先，只推进一个最小表达闭环</p></div>
            <div className="task-grid">{tasks.map((task, i) => <article className={`task-card ${task.tone}`} id={`task-${i + 1}`} key={task.number}><span className="task-number">{task.number}</span><h3>{task.title}</h3><p>{task.body}</p><div className="task-meta"><span>第一步</span><strong>{task.first}</strong></div><div className="task-time">{task.time}</div></article>)}</div>
            <div className="time-block-heading" id="schedule-heading"><div><p className="eyebrow">TIME BLOCKS</p><h3>今日时间块</h3></div><p>保留恢复与缓冲，不把全天排满</p></div>
            <section className="schedule" id="schedule"><div><span>上午 / 起床后</span><p>补水、正常进食、洗漱和短暂走动。若仍困倦或不舒服，继续休息；不空腹运动，也不使用高咖啡因饮品硬顶。</p></div><div><span>下午</span><p>只做一件表达任务：写一句锚点、一个真实场景和两条原始证据，再录一段 60 秒音频。不要同时追求完整脚本、录像、剪辑和发布。</p></div><div><span>晚上</span><p>回听一次，标记最影响理解的一处；如果精力允许再修一处。其余时间留白，提前停止信息流和工作，为睡眠留下至少一小时缓冲。</p></div></section>
            <details className="brief-item" id="risk"><summary><span className="brief-index">风险</span><span className="brief-main"><span className="pill">今日边界</span><strong>最可能让计划失效的三个触发点</strong><span>看清触发点，不增加任务</span></span><span className="plus">＋</span></summary><div className="brief-content"><p><strong>把疲惫解释成必须硬撑：</strong>恢复不是拖延；但恢复指吃饭、补水、休息和轻度活动，不是通宵游戏或无限刷信息。</p><p><strong>继续寻找“到底怎么做”：</strong>今天不需要另一套方法。先用已经有的材料完成一次解释，表达中的卡点会告诉你下一步缺什么。</p><p><strong>担心说错而不开始：</strong>第一版只是一项测试，不是定论。可以保留适用范围和待核验处，不要求今天公开发布。</p></div></details>
          </section>

          <section className="section" id="briefing">
            <div className="section-heading"><div><p className="eyebrow">DAILY INFORMATION</p><h2>每日资讯</h2></div><p>完整搬运云端《产品与创作每日简报｜2026 年 8 月 6 日》</p></div>
            <div className="section-context"><p><strong>本期主要核验范围：2026 年 8 月 5 日。</strong></p><p><strong>今日核心判断：</strong>平台正在同时做两件看似矛盾的事：一方面大规模吸纳创作者与 AI 内容，另一方面又加强对低质量合成内容、身份透明度和平台风险的治理。接下来的竞争重点不是“谁生成得更多”，而是谁能证明内容有来源、有人格、有判断，并且能持续形成真实用户价值。</p></div>
            <div className="brief-list">{creatorUpdates.map((item, i) => <details className="brief-item" id={`creator-${i + 1}`} key={item.tag}><summary><span className="brief-index">人</span><span className="brief-main"><span className="pill">{item.tag}</span><strong>{item.title}</strong><span>{item.intro}</span></span><span className="plus">＋</span></summary><div className="brief-content">{item.content.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<SourceLink href={item.source} label={item.sourceLabel} /></div></details>)}</div>

            <div className="section-heading compact-heading"><div><p className="eyebrow">YESTERDAY&apos;S STORIES</p><h2>行业重要新闻：5 条</h2></div><p>云端早报完整正文</p></div>
            <div className="brief-list">
              <details className="brief-item" id="story-1"><summary><span className="brief-index">01</span><span className="brief-main"><span className="pill">创作者平台</span><strong>Disney 与 TikTok 合作，正式把经典 IP 交给创作者二次生产</strong><span>授权素材、二次创作与平台筛选正在构成新的 IP 实验网络。</span></span><span className="plus">＋</span></summary><div className="brief-content"><p>Disney 与 TikTok 推出美国地区试点，部分创作者可使用 Disney、Pixar、Marvel 和 Star Wars 的授权素材创作短视频；部分作品还可能进入 Disney+ 的竖屏内容产品。</p><p>这不是一次普通的素材授权，而是娱乐公司对内容生产权的一次重新分配。</p><p>过去的 IP 运营链路是：公司制作 → 平台分发 → 用户观看。现在正在变成：公司提供世界观和素材 → 创作者重新解释 → 用户参与传播 → 平台筛选高反馈内容。</p><p><strong>产品思维：</strong>Disney 实际上在把创作者变成一种低成本、高频率的内容实验网络。公司不需要提前判断所有角色、情节和表达方式是否受欢迎，而是让大量创作者在真实平台环境中测试。</p><p><strong>用户洞察：</strong>用户关注的不只是官方故事，还关注：我熟悉的角色如何进入当下语境；普通人怎样重新演绎这个角色；这个 IP 能否成为我的表达工具；我能不能参与，而不只是观看。</p><p><strong>对你的启发：</strong>知识内容同样可以从“完整输出答案”转向“提供可二次使用的认知素材”。例如介绍一个概念时，可以同时提供一句话定义、一个个人案例、一个反例、一个可套用问题，以及一个邀请用户补充的开放缺口。这样用户更容易参与，而不是看完即走。</p><SourceLink href="https://newsroom.tiktok.com/" label="TikTok Newsroom" /></div></details>
              <details className="brief-item" id="story-2"><summary><span className="brief-index">02</span><span className="brief-main"><span className="pill">身份透明</span><strong>AI 虚拟博主进入监管与平台限制阶段</strong><span>透明、责任归属与长期信任正在成为合成内容的产品问题。</span></span><span className="plus">＋</span></summary><div className="brief-content"><p>Wired 报道，AI 虚拟博主市场仍在增长，但欧盟 AI 法规、平台标记机制和反 AI 垃圾内容策略正在提高透明度要求。TikTok、Meta、Pinterest 等平台都在强化对合成内容的识别、标记或分发限制。</p><p><strong>产品问题：</strong>虚拟博主过去的卖点主要是永远可用、不会出现真人丑闻、可批量生产、品牌控制力强。但这些优势会带来新的信任问题：用户究竟在与一个角色互动，还是在与一个没有披露身份的营销系统互动？</p><p><strong>用户研究视角：</strong>用户未必排斥虚拟角色，但通常会排斥被欺骗。透明披露可能降低短期神秘感，却能减少长期信任损耗。未来虚拟内容的竞争点不会只是“像不像真人”，而是身份是否清楚、角色设定是否一致、内容是否有持续价值、用户是否知道背后由谁负责、商业关系是否可追踪。</p><p><strong>对创作者的启发：</strong>使用 AI 辅助创作时，不需要机械强调“这是 AI 做的”，但应该明确自己的责任边界：哪些材料由 AI 整理；哪些判断来自自己；哪些内容尚未核验；哪些观点只是阶段性理解。可信度来自责任归属，而不是完全不用 AI。</p><SourceLink href="https://digital-strategy.ec.europa.eu/en/news/commission-publishes-code-practice-marking-and-labelling-ai-generated-content" label="欧盟委员会：AI 生成内容标记与标签实践准则" /></div></details>
              <details className="brief-item" id="story-3"><summary><span className="brief-index">03</span><span className="brief-main"><span className="pill">平台战略</span><strong>Disney 想把 Disney+ 做成“超级应用”，创作者成为用户生命周期的一部分</strong><span>内容、游戏、商品、个性化体验与创作者内容被放进一段关系里衡量。</span></span><span className="plus">＋</span></summary><div className="brief-content"><p>Disney CEO 在内部备忘录中提出，希望把 Disney+ 扩展为包含内容、游戏、商品和个性化体验的综合入口，并强调 AI 应服务于人类创作者。Disney 同时通过 TikTok 合作引入创作者生产内容，希望提升用户参与和长期价值。</p><p><strong>产品思维：</strong>这里的核心指标不是用户今天看了多少分钟，而是“终身粉丝价值”：看内容、参与讨论、创作二次内容、购买商品、玩游戏、参加线下体验。一个平台一旦围绕用户完整关系设计，就不再只优化单次点击。</p><p><strong>对你的启发：</strong>每日简报也可以用同样方式重新理解。它不只是每天阅读一次的内容，而可以成为选题入口、知识库资料、视频脚本证据、周复盘数据、产品趋势记录和后续商业判断依据。真正需要优化的不是每天写得多漂亮，而是同一份内容能否进入后续行动。</p><SourceLink href="https://www.techradar.com/streaming/disney-plus/disney-ceo-josh-damaro-wants-to-merge-disney-into-a-super-app-but-its-not-as-thrilling-as-youd-think-instead-youll-be-forced-to-see-ads-pushing-theme-parks-and-cruise-lines-and-who-really-wants-that" label="Disney+ 超级应用背景报道" /></div></details>
              <details className="brief-item" id="story-4"><summary><span className="brief-index">04</span><span className="brief-main"><span className="pill">用户研究</span><strong>YouTube 开始让创作者用自然语言搜索评论</strong><span>评论区从管理对象逐渐变成可查询的用户研究数据库。</span></span><span className="plus">＋</span></summary><div className="brief-content"><p>YouTube 近期更新显示，YouTube Studio 正增加按主题或语义搜索评论的能力。创作者可以输入问题、选择建议主题或查找相似评论，以便进行分析、互动和管理。</p><p>这虽然不是 8 月 5 日单日首发消息，但它是近期最值得产品与用户研究关注的平台变化之一。</p><p><strong>产品思维：</strong>过去的评论区工具主要解决排序、删除、点赞和回复。现在平台开始把评论区变成一个可查询的用户研究数据库。创作者可以不再逐条阅读，而是直接问：用户最常质疑什么、哪类人认为内容太难、哪些案例最容易引发共鸣、用户希望下一条讲什么、哪些评论表达的是同一个需求。</p><p><strong>适用边界：</strong>语义聚类能降低阅读成本，但不能代替人工判断。高频评论不一定代表最重要问题，少量但具体的反馈可能更接近真实需求。</p><p><strong>对你的实践建议：</strong>发布前三条 AI 知识库视频后，可以人工建立一个极简评论表：用户原话｜表面问题｜背后需求｜下一条内容。例：资料少也要搭吗｜工具选择｜不想浪费时间｜哪些人不需要知识库；会不会乱回答｜准确性｜害怕错误决策｜如何核验知识库；手机能做吗｜使用门槛｜想低成本开始｜手机版最小方案。这比只看播放量更接近用户研究。</p><SourceLink href="https://www.socialmediatoday.com/news/youtube-adds-ai-powered-comment-filtering/823939/" label="YouTube Studio 评论语义筛选报道" /></div></details>
              <details className="brief-item" id="story-5"><summary><span className="brief-index">05</span><span className="brief-main"><span className="pill">内容治理</span><strong>AI 内容泛滥正在迫使平台重新定义“原创”</strong><span>平台打击的不是工具，而是批量、重复、低价值与高判断成本。</span></span><span className="plus">＋</span></summary><div className="brief-content"><p>近期多家平台开始限制低质量、批量化 AI 内容。YouTube 强调无法货币化的对象是重复、批量、缺乏原创价值的内容，而不是所有使用 AI 的内容；TikTok、Pinterest、Meta、Substack 和 Snap 也在增加标签、检测或推荐限制。</p><p><strong>产品与内容判断：</strong>平台真正打击的不是 AI，而是内容生产成本趋近于零、用户判断成本却越来越高、大量内容互相重复、推荐系统难以识别真实价值、真人原创内容被批量内容淹没。</p><p>因此平台正在重新提高“原创”的定义：不只是素材第一次出现，而是内容是否包含新的判断、经验、结构或表达。</p><p><strong>对你的启发：</strong>不必担心使用 AI 会自动失去原创性。更需要检查的是：是否有真实场景、是否有具体证据、是否指出工具的限制、是否做出了选择、是否产生了新的可执行结论。AI 可以帮助组织材料，但不能替人承担判断。</p><SourceLink href="https://blog.google/intl/en-in/products/platforms/improving-ai-labels-for-viewers-and-creators/" label="YouTube / Google：AI 内容标签说明" /></div></details>
            </div>

            <details className="brief-item" id="product-observation"><summary><span className="brief-index">观察</span><span className="brief-main"><span className="pill">产品观察</span><strong>创作者平台正在把“内容”变成可计算的用户研究对象</strong><span>从播放、点击和停留，扩展到原创、透明、需求与用户生命周期。</span></span><span className="plus">＋</span></summary><div className="brief-content"><p>今天最值得注意的趋势，不是 Disney、TikTok 或 YouTube 各自推出了什么功能，而是平台对内容价值的计算方式正在变化。</p><p>过去平台主要计算播放、点击、停留、点赞和分享。现在开始增加内容是否原创、身份是否透明、评论中出现了什么需求、用户是否从观看进入创作、内容是否提高用户生命周期价值、AI 是否降低了质量和信任。</p><p>这意味着创作者也应该升级自己的数据观。不要只问“这条内容为什么没有爆？”，更应该问“用户在哪一步没有继续？”</p><p>例如：看到了但没有理解；理解了但不相信；相信了但认为与自己无关；认为有关但不知道下一步怎么做；想行动但工具门槛太高。这五个断点，比单纯的播放量更能指导下一条内容。</p></div></details>
            <details className="brief-item" id="early-action"><summary><span className="brief-index">行动</span><span className="brief-main"><span className="pill">今日行动建议</span><strong>完成一条不依赖完整正确答案的 AI 知识库视频草稿</strong><span>用原始证据、人工判断和低风险决策，把检索接进实际行动。</span></span><span className="plus">＋</span></summary><div className="brief-content"><p><strong>建议选题：</strong>我发现 AI 知识库最重要的功能，不是帮我找到资料，而是暴露我反复思考却没有决策的问题。</p><p><strong>1. 具体场景：</strong>展示近期多次记录过的同一个问题：我想做知识博主，但一直担心自己的观点不正确。</p><p><strong>2. 知识库检索：</strong>让知识库寻找过去一个月中所有涉及不敢发布、担心观点错误、继续输入、没有行动、等待准备好的原始记录。</p><p><strong>3. 不直接接受 AI 总结：</strong>只展示 2—3 条原始证据，然后由自己判断：我的卡点不是没有观点，而是不允许观点处于可修改状态。</p><p><strong>4. 做出一个低风险决策：</strong>今天只发布一个带边界的阶段性观点：这是我目前的理解，它可能不完整，但我会根据真实反馈继续修正。</p><p><strong>5. 结尾：</strong>以前我以为知识库是让我记住更多东西。现在我发现，它更像一面镜子：让我看到有些问题，我已经思考了很多次，只是一直没有决定。</p><p>这条内容的价值不是展示工具多先进，而是展示：AI 如何帮助一个人从重复思考进入实际决策。</p></div></details>
          </section>

          <section className="section planet-section" id="planet">
            <div className="section-heading"><div><p className="eyebrow">JIANGHU NOTES</p><h2>姜胡说</h2></div><p>昨日知识星球原文与小报童原文</p></div>
            <p className="section-context">昨日知识星球归档区间：2026-08-04 23:30 至 2026-08-05 23:30</p>
            <details className="planet-card" id="planet-1"><summary><div className="avatar">胡</div><div><span className="planet-time">大胡子 · 2026-08-05 10:47</span><strong>mcp_vault：每次输入都重新编织知识</strong><span>点击展开星主完整原文与 6 张原始图片</span></div><span className="open-label">原文</span></summary><div className="planet-content"><div className="original"><span>星主原文</span><p>这个是方向，不是现在要做的事。<br />看不懂也没关系。</p><p>mcp_vault是我自己构建的服务，就是之前和大家说的第5层：既可以自己检索，也可以发布出来给外部使用；<br />姜小胡就是通过它利用我的知识系统的。</p><p>每一次我输入一条信息后，系统就会启动mcp_vault找到之前所有与此相关的知识卡片和原子，重新融合、编织，纠偏、补全、完善；然后重构。<br />每一次知识的输入，不再只是生成一张知识卡片或者新建一条原子那么简单。它会带来对该知识领域的一次重构，重新理解。</p><div className="planet-gallery">{[1,2,3,4,5,6].map(n => <img key={n} src={`/daily-briefing/knowledge/2026-08-05/images/[1] 大胡子 -${n}.png`} alt={`大胡子原始配图 ${n}`} />)}</div><SourceLink href="/daily-briefing/knowledge/2026-08-05/26-08-05姜胡说知识星球.md" label="查看 8 月 5 日原始归档" /></div></div></details>
            <details className="planet-card" id="planet-2"><summary><div className="avatar">胡</div><div><span className="planet-time">大胡子 · 2026-08-05 11:52</span><strong>阅读不是输入，是拆解思考过程</strong><span>点击展开星主完整原文</span></div><span className="open-label">原文</span></summary><div className="planet-content"><div className="original"><span>星主原文</span><p>大多数人的阅读方法从根上就错了。<br />以为阅读是“输入”，把书当U盘，拼命往里存。存完就忘，读了和没读一样；看了就和没看一样。</p><p>真正的阅读是拆解。把书当成“思考过程的样品”，你的任务不是收藏，是拆开它，看看作者是怎么想的。</p><p>怎么拆？<br />三个零件：论点、论据、逻辑脉络。<br />论点就是头——作者想证明什么。<br />论据就是四肢——作者用什么支撑（案例、数据、推理）。<br />逻辑脉络就是躯干——论据怎么组织起来推向论点。<br />读完一章，问自己“作者的论点是什么，结论是什么？论据是什么”。<br />答不上来，就说明你还没读懂。</p><p>怎么把知识串连起来呢？<br />知识点不是珠子，是叶子。<br />先找到树干（这本书解决什么问题），再找大枝（核心答案分几个层面），叶子自然挂上去。<br />顺序错了，永远被细节淹没。</p><p>很多人一年读几十本，合上书说不出任何自己的判断。<br />不是不够努力，是方法反了。<br />读书不是下载，是让脑子长出结构。</p><SourceLink href="/daily-briefing/knowledge/2026-08-05/26-08-05姜胡说知识星球.md" label="查看 8 月 5 日原始归档" /></div></div></details>
            <details className="planet-card" id="planet-3"><summary><div className="avatar">胡</div><div><span className="planet-time">大胡子 · 2026-08-05 14:13</span><strong>知识库的三个关键要素</strong><span>点击展开星主完整原文与原始图片</span></div><span className="open-label">原文</span></summary><div className="planet-content"><div className="original"><span>星主原文</span><p>知识库的三个关键要素。</p><p>一、捕获层。解决“知识从哪儿来的问题”。<br />目标是零摩擦——随时随地进系统，不需要想“放哪个文件夹”。它应该是自动完成的。</p><p>二、检索层。解决“知识怎么用的问题”。<br />三种模式共存：知道时间走时间线，知道概念走链接，知道内容但不知道关键词走语义搜索。当你的系统有语义搜索能力时，就不需要主动建立链接了。</p><p>三、涌现层。解决“怎么发现没想到的问题”。<br />知识库真正的价值不在“存了多少”，在“发现了什么关联”。<br />同一个概念被反复提到超过3次，把它聚合起来。聚合的内容超过15条高质量链接，升级成主题笔记。</p><img src="/daily-briefing/knowledge/2026-08-05/images/[3] 大胡子 -1.png" alt="大胡子原始配图" /><SourceLink href="/daily-briefing/knowledge/2026-08-05/26-08-05姜胡说知识星球.md" label="查看 8 月 5 日原始归档" /></div></div></details>
            <details className="planet-card" id="xiaobaotong-1"><summary><div className="avatar">读</div><div><span className="planet-time">小报童 · 姜胡说 · 2026-08-03 17:40:51</span><strong>你报了口才班还是不会说，因为缺少一个锚点</strong><span>点击展开本地采集的完整原文</span></div><span className="open-label">原文</span></summary><div className="planet-content"><div className="original"><span>小报童原文</span><p>报了口才班，练了绕口令，面对镜头还是磕磕巴巴。你以为是嘴巴的问题；真正的原因是：脑子没想清楚。</p><h3>脑子没想清楚</h3><p>你真正要练的是输出力。写文章是输出力。拍视频是输出力。直播是输出力。跟客户沟通也是输出力。</p><p>口才是输出力的冰山一角，水面下的结构才是关键。</p><p><strong>口才训练营大多解决的是“敢说”的问题，解决不了“会说”的问题。</strong>“会说”的前提是什么？你脑子里本身就有结构。大多数人以为是嘴的问题，跑去练嘴。练再久，都不会有结果。</p><p>因为根儿就不在嘴上。</p><h3>输出力分四层</h3><p>第一层，写。思考的过程，能不能把一件事写清楚。第二层，说。梳理的过程，能不能实时对话，不卡壳。第三层，教。验证的过程，能不能把复杂的东西讲给小白听。第四层，拍。输出的过程，能不能对着镜头讲清楚。</p><p>先思考（写）→ 再梳理（说）→ 验证自己懂了（教）→ 最后输出（拍）。</p><p><strong>大多数人是越过了前三层，直接跑去做第四层。一定会不舒服。</strong></p><p>正确的流程就一句话：先写清楚，再往下走。写的时候通顺，读出来不通顺——说明逻辑链有问题。回去改结构，不是硬背逐字稿。写清楚了，说和教自然就顺了。拍只是前三层的输出。这一条，能解决你80%的问题。</p><h3>写不出来</h3><p>大部分都是想一步到位。你问一个人：“你会画画吗？”他通常会回答说不会。怎么可能不会画呢？你一岁不到的时候就已经会画了。你说的不会画是指画得不好看。因为觉得自己画得不好看，所以就不画了。这就是你不会画画的原因。</p><p>你会写吗？当然会写。说不会写是写的不好。所以就不写了。</p><p>你不需要写得好。你只需要写出来。写成流水账也没问题，事实上，你一开始完全可以写成流水账。好，是后面的事。甚至是几个月以后的事儿。</p><p>你写不出来，另一个更深层次的原因，不是因为你不会写。是你不知道自己这条<strong>到底要表达什么</strong>。这叫锚点缺失。<strong>锚点就是你的评判标准。</strong>没有锚点，所有方法论都是悬空的。</p><p>就会出现昨天社群老伙计的那个“不会拆爆款、不会数据分析、发完视频不会一个一个测变量”的问题。</p><p>你以为你缺的是方法。你缺的是目标。拆了一百个爆款，不知道为什么要拆。学了一堆拍摄技巧，不知道自己的视频要传递什么。每天更新，不知道“好”的标准是什么。</p><h3>锚点缺失的人，长什么样</h3><p><strong>第一种：拼数量。</strong><br />“我做了50条视频，比他多，为什么他爆了我不爆？”你的标准是“做了多少”。正确的标准是“影响力”。一条视频，影响了一个人，比你发50条没人看有价值。</p><p><strong>第二种：什么火做什么。</strong><br />今天学口播，明天学Vlog，后天学剧情。换了一圈，发现没有一条是自己真正想做的。没有锚点，任何方法都像救命稻草。</p><p><strong>第三种：写不出一句话总结。</strong><br />“这条视频帮什么人解决什么问题？”——你答不上来。这不是文笔问题，是锚点问题。</p><p><strong>锚点（知道去哪）→ 输出力（知道怎么组织）→ 口才（知道怎么表达）</strong><br />顺序不能乱。否则，漂移玩得再帅，你也到达不了目的地。你连目的地在哪儿都不知道。</p><h3>应该怎么拍视频呢</h3><p><strong>第一步，定锚点。</strong><br />拍摄之前，问问自己：“这条视频能给用户带来什么，我希望观众看完记住什么？”</p><p>这句话就是你的锚点。回答不出来，不要开拍。后面的脚本、节奏、画面、语调——都围绕它展开。锚点定了，标准就定了。</p><p>锚点还有一个更实际的作用：这条视频好在哪儿？数据会怎么样？收藏率、评论量、分享率……为什么？猜对了，记下来。猜错了，下次调整。</p><p>人的大脑就是一台推测机器。它代表了你对这件事情的理解。有推测，才有验证。有验证，才能找到你理解的世界与真实世界的偏差。这才是真正的积累。</p><p><strong>第二步，写脚本。</strong><br />有了锚点，写脚本就是“怎么把这件事讲清楚”。开头，一句话抛锚点。中间，展开论证。结尾，把锚点再强调一遍。</p><p>我个人经常使用的结构是：开头（吸引+洞见）+中间（解决方案）+结尾（金句）。</p><p>你不需要逐字稿。你需要结构。结构清楚了，根本不需要背，因为是你自己的逻辑。</p><p>试着说出来、讲给别人（这个别人很可能是空气）听。通不通顺，有没有卡顿的地方。</p><p>录是最后一步。</p><p><strong>第三步，录。</strong><br />写清楚了，录就是把它说出来。卡了，不要硬背。回去看结构：是不是逻辑链断了？是不是跳过了某一步？</p><p><strong>90%的卡壳，是结构问题，不是嘴的问题。</strong></p><p>对新手来说，我个人建议不要一上来就录。至少分两次，一次是录音，一次是录像。</p><p>录音的时候相对单纯一点。去掉所有的无关因素，就是把道理讲清楚。然后把录音的文本发送给AI，重新再过一遍：我的锚点是什么？我怎样把这件事情讲清楚？有更好的方法吗？</p><p>然后才是录像。</p><p>有准备的人和没准备的人是完全不一样的。花时间认真准备的人和仅仅是准备了的人是不一样的。</p><h3>总结一哈</h3><p><strong>口才不好 → 输出力不足 → 锚点缺失。</strong>根因在锚点。</p><p>没有锚点，所有方法都是悬空的。知道要去哪儿，自然就知道该怎么做了。</p><SourceLink href="https://xiaobot.net/post/0fe35cec-f8be-477e-ae8f-59e35ad887c6" label="小报童原文" /></div></div></details>
          </section>

          <section className="section" id="review">
            <div className="section-heading"><div><p className="eyebrow">PERSONAL REVIEW</p><h2>复盘</h2></div><p>事实与 AI 建议分开呈现</p></div>
            <div className="review-grid">
              <details className="review-card" id="yesterday-review" open><summary>昨日复盘</summary><div><p><strong>事实：</strong>8 月 5 日日记记录“祝我生日快乐”，约四点入睡；之后去七星路帮姐姐喂猫，处理猫砂、快递、换猫砂和打扫麻将馆，原预计半小时的事延长，因而没有去游泳。晚上在家补看《蜘蛛侠》前两部。</p><p><strong>完成与未完成：</strong>日记记录了照料、清洁、取快递和外出体力劳动；没有记录新的视频成品、公开发布、知识库使用结果或外部反馈。没有将“没有成品”写成“昨天什么也没完成”。</p><p><strong>精力信号：</strong>有四点入睡和白天较多体力劳动的记录。仅据这些记录不能作医学归因，但今天计划应主动缩量、保留恢复。</p><p><strong>可延续的模式：</strong>日记里能具体记录发生的事、预期和实际的差异；这类原始材料是后续复盘与内容证据。</p><p><strong>需要避免的模式：</strong>不要在睡眠负荷已高时，同时要求完成脚本、录制、剪辑、发布和系统维护。把一项表达拆成锚点、录音、修一处，比再增加输入更现实。</p><p className="advice"><strong>AI 建议：</strong>今天的关键推进只保留一个可修改的 60 秒音频；其余恢复不属于拖延。</p></div></details>
              <details className="review-card" id="seven-day-trend"><summary>近七天趋势</summary><div className="trend-list"><div><strong>重复目标</strong><p>近七天反复出现的主线是：把 AI、知识库、每日简报与真实工作连接起来，完成 AI 知识库视频，并从输出与反馈中培养内容能力。</p></div><div><strong>重复阻碍</strong><p>系统搭建、故障排查、直播输入、游戏与信息流持续挤占精力；当输出涉及外部评价时，记录中反复出现继续准备、继续验证或担心观点不正确。</p></div><div><strong>精力变化</strong><p>一周内多次出现通宵、晚睡、白天补觉和茶饮后失眠；8 月 4 日还记录游泳时疲惫、不舒服。恢复应是今天的计划前提。</p></div><div><strong>已形成的资产</strong><p>每日简报、知识星球采集、财务工作台、教程、视频脚本和直播笔记都已存在。当前缺口更接近可观看草稿与真实反馈，而不是新的系统。</p></div></div></details>
              <details className="review-card diagnosis" id="action-diagnosis"><summary>AI 执行力诊断 / 建议</summary><div><p><strong>证据：</strong>8 月 2 日日记明确写到“因为害怕自己是错的，所以不敢发出去”；8 月 4 日记录了大量直播输入与概念整理，并写到“道理我也不爱听，我也想听到底怎么做”；近一周已有教程、脚本、知识星球采集和简报系统，但日记中稳定的公开测试记录仍较少。8 月 5 日主要是生日与照料事务，不能把当天没有产出直接归因于回避。</p><p><strong>信号判断：</strong>按 dbs-action 的阿德勒框架，信号 B（思考 / 整理成为行动替代）、信号 D（继续输入带来“正在进步”的安全感）、信号 E（把发布理解为接受正确性评价）在此前记录中出现。睡眠和真实生活负荷同样存在，不把全部未行动简化为心理问题。</p><p><strong>AI 诊断：</strong>更安全的选择往往是继续找更具体的方法，因为方法越多，越可以推迟一次会暴露理解漏洞的表达。若“想理解”没有经过讲给别人、接受追问和修改，它仍只是准备。</p><p><strong>真正的问题：</strong>能否让一个具体对象听见一个并不完整的版本，并把对方的困惑当作下一轮学习材料，而不是把它当成对个人能力的判决。</p><p><strong>处方：</strong>今天只录音，不强制发布。完成后只检查两项：这句话具体帮助谁；听者会不会知道下一步做什么。若其中一项不清楚，只修对应一处。</p><p><strong>适用边界：</strong>若持续出现明显不适、眩晕、心悸或日常功能受影响，应停止高强度任务并考虑寻求专业医疗建议。恢复身体不属于拖延。</p><p><strong>免责声明：</strong>这是基于 dbs-action 框架和本地日记证据生成的 AI 诊断 / 建议，不是心理咨询或医疗诊断。</p></div></details>
            </div>
          </section>

          <section className="section" id="deep-reads"><div className="section-heading"><div><p className="eyebrow">DEEP READS</p><h2>今日深读</h2></div><p>云端早报推荐的 3 篇原文，任选一篇</p></div><div className="brief-list deep-read-list">
            <details className="brief-item" id="deep-read-1"><summary><span className="brief-index">01</span><span className="brief-main"><strong>Wired：AI 虚拟博主进入监管时代</strong><span>阅读问题：用户真正介意的是角色不真实吗，还是平台和创作者隐瞒了角色的真实生产方式？</span></span><span className="plus">＋</span></summary><div className="brief-content"><p>适合从身份透明、用户信任和合成内容商业化角度阅读。</p><SourceLink href="https://www.wired.com/category/politics/policy/" label="WIRED：AI 政策与透明度报道" /></div></details>
            <details className="brief-item" id="deep-read-2"><summary><span className="brief-index">02</span><span className="brief-main"><strong>Disney 与 TikTok 的 IP 创作者合作</strong><span>阅读问题：一个内容品牌应把多少控制权交给用户和创作者，才能获得参与，又不损害核心价值？</span></span><span className="plus">＋</span></summary><div className="brief-content"><p>适合观察大型内容公司如何把创作者变成产品实验、分发和用户参与的一部分。</p><SourceLink href="https://newsroom.tiktok.com/" label="TikTok Newsroom" /></div></details>
            <details className="brief-item" id="deep-read-3"><summary><span className="brief-index">03</span><span className="brief-main"><strong>AI 与出版行业快速证据综述</strong><span>阅读问题：讨论 AI 时，是在讨论它“看起来能做什么”，还是在验证它在真实任务中是否稳定可靠？</span></span><span className="plus">＋</span></summary><div className="brief-content"><p>这份研究分析了 2025 年 11 月至 2026 年 8 月间 89 篇关于 AI 与出版的行业报道。作者发现，行业讨论大量集中在版权、许可和产品发布，但对模型评估、检索增强、提示注入、智能体可靠性、溯源和真实工作流测试讨论不足。</p><SourceLink href="https://arxiv.org/abs/2608.00964" label="研究原文" /></div></details>
          </div></section>

          <section className="section" id="hotlist"><div className="section-heading"><div><p className="eyebrow">HOT LIST</p><h2>热点榜单</h2></div><p>2026 年 8 月 5 日完整榜单</p></div><a className="hotlist" href="/daily-briefing/hotlist/2026-08-05.html" aria-label="打开热点榜单"><span>昨日榜单</span><strong>查看 2026 年 8 月 5 日完整榜单</strong><span className="arrow">↗</span></a></section>
          <footer><p>先让节律恢复，<br />再让一个可修改的版本出现。</p><span>每日 08:30 更新 · 完整内容折叠保存</span></footer>
        </div>
      </div>
    </main>
  );
}
